# Generated by Django 5.1.7 on 2025-03-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, upload_to='student/'),
        ),
    ]
