# Generated by Django 5.1.7 on 2025-03-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='JnRrefGMVXicw55hylsJO7fZ8TvQXepM', editable=False, max_length=32, unique=True),
        ),
    ]
