# Generated by Django 5.1.7 on 2025-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gsXlZJFIQ3KFn5CLOuw3Y9V4N1gyMRHl', editable=False, max_length=32, unique=True),
        ),
    ]
